//
// Created by Joachim on 14/02/2023.
//

#ifndef INFO_F209_GR5_2022_PLAYER_STATUS_HPP
#define INFO_F209_GR5_2022_PLAYER_STATUS_HPP

enum PLAYER_STATUS {
    FREE,
    JAILED,
    LOST,
    IN_EXCHANGE,
    WAITING_FOR_AUCTION_TURN,
    AUCTION_TURN,
    BANKRUPT_SUSPECTED,
    BANKRUPT_CONFIRMED,
    DEBT,
    OTHER };

#endif //INFO_F209_GR5_2022_PLAYER_STATUS_HPP
