name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: libs
      run: sudo apt install libsfml-dev libncurses5-dev libjsoncpp-dev && sudo ln -s /usr/include/jsoncpp/json/ /usr/include/json
    - name: make
      run: cd src && make server GUI CUI CLI
